### ISSUE TITLE
the paper could not be found

### ISSUE THREAD

**Issue by lumeixia** [QinbinLi/FedKT#1]
Hello, sorry to bother you,  I can't find your paper in Google academic.I found the author's home page but also could not find it. Could you please take the liberty to send a copy to me? My email is 876390031@qq.com .Thank you.

**Comment by QinbinLi** [comment]
Hi @lumeixia ,

The paper is currently not available. We will upload the paper to arxiv recently. Thanks.

**Comment by QinbinLi** [comment]
Hi @lumeixia ,

The paper is now available [here](https://arxiv.org/pdf/2010.01017.pdf).
